### ISSUE TITLE
Jenkins pipeline integration

### ISSUE THREAD

**Issue by solevic** [jenkinsci/fabric-beta-publisher-plugin#16]
In the current state, it is not possible to distribute fabric betas through a jenkins pipeline using a jenkinsfile.

It would require to implement SimpleBuildStep into the FabricBetaPublisher recorder.

https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md

**Comment by egor-n** [comment]
Closed with #17 – will be released in 1.7
