### ISSUE TITLE
Make Pipeline support prettier

### ISSUE THREAD

**Issue by egor-n** [jenkinsci/fabric-beta-publisher-plugin#22]
`@Symbol("fabric")` should work just fine or override `String getFunctionName()` and return `"fabric"` there.

**Comment by PabloThiele** [comment]
Could you please at least add how to proceed to use the plugin using the pipeline today? After installed (version 1.8) I'm not able to see any snippet option of find some on the readme. 
Could you please add on the readme a happy path example using pipeline? Thanks.

**Comment by egor-n** [comment]
@PabloThiele basic usage looks like this:
```groovy
step([
    $class: 'FabricBetaPublisher',
    apiKey: "your_api_key",
    apkPath: "app/build/outputs/apk/*.apk",
    buildSecret: "your_build_secret",
    notifyTestersType: 'NOTIFY_TESTERS_GROUP',
    releaseNotesType: 'RELEASE_NOTES_TYPE_FILE',
    releaseNotesFile: "your_release_notes_file.txt",
    testersGroup: "your_testers_group",
    organization: "your_organization",
    useAntStyleInclude: true
])
```

**Comment by mtrakal** [comment]
For other people:

apiKey = buildSecret from fabric.properties files
buildSecret = properties from AndroidManifest.xml file (io.fabric.ApiKey)
notifyTestersType = can be NOTIFY_TESTERS_TYPE_EMAILS or NOTIFY_TESTERS_GROUP
releaseNotesType = RELEASE_NOTES_TYPE_NONE, RELEASE_NOTES_TYPE_PARAMETER (require: releaseNotesParameter), RELEASE_NOTES_TYPE_CHANGELOG, RELEASE_NOTES_TYPE_FILE (require: releaseNotesFile)

**Comment by mtrakal** [comment]
in https://github.com/jenkinsci/fabric-beta-publisher-plugin/issues/22#issuecomment-325104548 is wrong 
`releaseNotesType: 'RELEASE_NOTES_TYPE_FILE',` it should be: `releaseNotesType: 'RELEASE_NOTES_FILE',`

THANKS FOR VERY WELL DOCUMENTATION...

**Comment by egor-n** [comment]
@mtrakal thank you! I have edited my comment.
