### ISSUE TITLE
Multiple tester groups

### ISSUE THREAD

**Issue by josedlpozo** [jenkinsci/fabric-beta-publisher-plugin#23]
Hello!

I was trying to add multiple tester groups separated by commas but the execution fails.Is it possible? If not, please let me know how can I help you to add this feature :smile: 

Thanks!

**Comment by egor-n** [comment]
It seems like it should work – what exception do you get?

**Comment by josedlpozo** [comment]
I got this log:

`Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it had a problem uploading the distribution.Could not find a group for one or more of: ["QA", "Android Development", "UX"]
`
My tester groups are QA, Android Development and UX and I wrote them separated by commas.

**Comment by egor-n** [comment]
This error means that one or more of the listed groups is not present in the Fabric Beta. Make sure all of them are spelled correctly and are present in "Manage Groups" section in Fabric Beta dashboard.

**Comment by josedlpozo** [comment]
Yes, I am sure that this three groups are present in Fabric beta tester groups. Now I am doubting if the space in 'Android Development' could make this to fail.

I will try removing it

**Comment by josedlpozo** [comment]
Nop, the space in the group name is not the problem.

These are two executed commands with space and without it...

```
Executing command: [java, -jar, /tmp/crashlytics-devtools8561197326643697331.jar, -androidRes, ., -apiKey, 6e3f5b35724da2f6c33bb8bda22995d900f22cfa, -apiSecret, f94dce7bd1a197a9c6e641bbd0ecee1835ce58c5527fba423019f6a04dc45a21, -androidManifest, /tmp/xml1339103222100697600.tmp, -uploadDist, /tmp/app-build-tmp471677613539245064apk, -betaDistributionNotifications, true, -betaDistributionGroupAliases, PluginTest, PluginFabricTest, -betaDistributionReleaseNotes, Prueba]

Executing command: [java, -jar, /tmp/crashlytics-devtools8185353106254614788.jar, -androidRes, ., -apiKey, 6e3f5b35724da2f6c33bb8bda22995d900f22cfa, -apiSecret, f94dce7bd1a197a9c6e641bbd0ecee1835ce58c5527fba423019f6a04dc45a21, -androidManifest, /tmp/xml3245760712591598032.tmp, -uploadDist, /tmp/app-build-tmp6544402396346579968apk, -betaDistributionNotifications, true, -betaDistributionGroupAliases, Plugin test, PluginFabricTest, -betaDistributionReleaseNotes, Prueba]
```

Maybe I am missing something..

**Comment by egor-n** [comment]
I have just checked and multiple tester groups work for me.

**Comment by josedlpozo** [comment]
@egor-n I have realized that I was writing the group name instead of the alias. Fabric wants the alias. Thank you for the answers :+1:

**Comment by egor-n** [comment]
Glad I could help!
