### ISSUE TITLE
Make .apk file path(s) allow entire folder

### ISSUE THREAD

**Issue by heutschibogdan** [jenkinsci/fabric-beta-publisher-plugin#25]
It would be nice to be able to upload all the files from one specific folder, for example app/build/outputs/apk/.
I am building different flavors (one flavor or more each time) and I would like to upload them to fabric, but the files count and name change depending on some build parameter.

**Comment by egor-n** [comment]
If you check the "path as ant-style include" checkbox and set the path value to "app/build/outputs/apk/*.apk", then it will upload all APKs from the folder.

**Comment by heutschibogdan** [comment]
Ok, Thank you, I haven't realized that.
