### ISSUE TITLE
Custom "Build_version"

### ISSUE THREAD

**Issue by Matthis2909** [jenkinsci/fabric-beta-publisher-plugin#39]
Hi,

For CI, I want custom `build_version`. I want add BRANCH_NAME at this value.

Is it possible with this plugin ?

**Comment by egor-n** [comment]
No, there's no way to set a custom build version using this plugin. What should be done instead:
1. In Jenkins set an environment variable to desirable build version (e.g. `CUSTOM_BUILD_NUMBER`)
2. Then, use it in the `build.gradle` by calling `System.getenv("CUSTOM_BUILD_NUMBER")`

**Comment by Matthis2909** [comment]
How you get `version_code` ? Where is this File ? I see you Zip `apkFile` but where is this `assets/crashlytic.properties` ?

**Comment by egor-n** [comment]
You shouldn't need the `version_code`. In you build.gradle file do something like:

```groovy
versionName 50 + getCustomVersionName()
```
